<section class="notice notice-information"><span class="notice-icon"><?= $symbol('info') ?></span><div><strong>Motor fiscal em desenvolvimento · versão 0.1</strong><p>O cálculo disponível é uma simulação matemática do Anexo I para operações comuns em 2026. Não substitui o PGDAS-D oficial.</p></div><a href="/?page=sobre">Ver limitações</a></section>
<section class="metrics-grid" aria-label="Indicadores locais">
    <div class="metric-card"><div class="metric-icon blue"><?= $symbol('folder') ?></div><div><div class="metric-label">Apurações salvas</div><div class="metric-value" id="metricSaved">—</div><div class="metric-foot">Neste navegador</div></div></div>
    <div class="metric-card"><div class="metric-icon green"><?= $symbol('checklist') ?></div><div><div class="metric-label">Competências registradas</div><div class="metric-value" id="metricPeriods">—</div><div class="metric-foot">Contagem local</div></div></div>
    <div class="metric-card"><div class="metric-icon amber"><?= $symbol('calculator') ?></div><div><div class="metric-label">Módulos disponíveis</div><div class="metric-value">01</div><div class="metric-foot">Anexo I, cenário comum</div></div></div>
    <div class="metric-card"><div class="metric-icon purple"><?= $symbol('lock') ?></div><div><div class="metric-label">Armazenamento central</div><div class="metric-value">Zero</div><div class="metric-foot">Para dados fiscais</div></div></div>
</section>
<div class="two-column dashboard-panels">
  <section class="panel"><div class="panel-header"><div><h2>Iniciar trabalho</h2><p>Ferramentas disponíveis na versão atual</p></div></div><div class="quick-tools">
    <a class="quick-tool" href="/?page=apuracao"><span class="quick-tool-icon blue"><?= $symbol('calculator') ?></span><span><strong>Simular PGDAS-D</strong><small>Calcular alíquota efetiva e repartição do Anexo I.</small></span><?= $symbol('arrow') ?></a>
    <a class="quick-tool" href="/?page=conferencia"><span class="quick-tool-icon green"><?= $symbol('file') ?></span><span><strong>Conferir arquivos NF-e</strong><small>Ler XMLs localmente, sem upload ao servidor.</small></span><?= $symbol('arrow') ?></a>
    <a class="quick-tool" href="/?page=regras"><span class="quick-tool-icon amber"><?= $symbol('book') ?></span><span><strong>Consultar tabelas tributárias</strong><small>Consultar faixas, percentuais e fontes oficiais.</small></span><?= $symbol('arrow') ?></a>
  </div></section>
  <section class="panel"><div class="panel-header"><div><h2>Últimas apurações</h2><p>Informações guardadas exclusivamente no seu navegador</p></div><a class="btn btn-mini btn-outline" href="/?page=historico">Ver todas <?= $symbol('arrow') ?></a></div><div class="table-scroll"><table class="data-table"><thead><tr><th>IDENTIFICAÇÃO</th><th>COMPETÊNCIA</th><th>RESULTADO</th></tr></thead><tbody id="recentRows"><tr><td colspan="3" class="table-empty">Carregando histórico local...</td></tr></tbody></table></div></section>
</div>
<section class="panel public-panel"><div class="public-panel-copy"><span class="eyebrow">PRIVACIDADE POR PADRÃO</span><h2>Use gratuitamente. Seus dados permanecem sob seu controle.</h2><p>Não há cadastro obrigatório. Você pode salvar trabalhos no navegador ou fazer um backup portátil criptografado.</p><a href="/?page=privacidade">Entenda como os dados são tratados <?= $symbol('arrow') ?></a></div><div class="public-panel-deco"><?= $symbol('shield') ?></div></section>
