<section class="notice notice-information"><span class="notice-icon"><?= $symbol('book') ?></span><div><strong>Regras de 2026 • versão <?= $esc($calc->rulesPublic()['versao']) ?></strong><p>O catálogo atual contém as tabelas do Anexo I. A 6ª faixa está documentada, mas não liberada para cálculo neste MVP devido ao tratamento de sublimites.</p></div></section>
<section class="panel"><div class="panel-header"><div><h2>Simples Nacional — Anexo I</h2><p>Tabela nominal de comércio vigente para referência em 2026</p></div><span class="pill pill-warning">CÁLCULOS NÃO HOMOLOGADOS</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>FAIXA</th><th>RBT12 ATÉ</th><th>ALÍQUOTA NOMINAL</th><th>PARCELA A DEDUZIR</th><th>DISPONIBILIDADE</th></tr></thead><tbody>
<?php foreach ($calc->rulesPublic()['faixas'] as $faixa): ?>
<tr><td><strong><?= $esc($faixa['numero']) ?>ª faixa</strong></td><td>R$ <?= $esc(number_format((int)$faixa['ate_centavos'] / 100, 2, ',', '.')) ?></td><td><?= $esc(number_format($faixa['aliquota_bps'] / 100, 2, ',', '.')) ?>%</td><td>R$ <?= $esc(number_format((int)$faixa['deducao_centavos'] / 100, 2, ',', '.')) ?></td><td><span class="pill <?= $faixa['numero'] <= 5 ? 'pill-success' : 'pill-warning' ?>"><?= $faixa['numero'] <= 5 ? 'Simulação disponível*' : 'Bloqueada no MVP' ?></span></td></tr>
<?php endforeach; ?>
</tbody></table></div><div class="note-in-panel">* Somente comércio comum, competência 2026, empresa estabelecida há mais de 12 meses e demais condições do motor. Não corresponde a homologação oficial.</div></section>
<section class="panel info-section"><div class="panel-header"><h2>Referências normativas oficiais</h2></div><div class="legal-links">
<?php foreach ($calc->rulesPublic()['referencias'] as $r): ?><a href="<?= $esc($r['url']) ?>" target="_blank" rel="noopener noreferrer"><?= $symbol('book') ?><span><?= $esc($r['nome']) ?></span><?= $symbol('external') ?></a><?php endforeach; ?>
</div></section>
